### ISSUE TITLE
Investigate possibility of correcting DDI schema validation errors

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/dataverse#32]
Possibly a spike (?) to learn more about the XML APIs that generate DDI XML for Dataverse 4.5 and evaluate the feasibility of correcting XML schema validation errors.

**Comment by johnhuck** [comment]
@piyapongch thinks he has found where to make these changes, so we should keep this issue active for the time being.

**Comment by piyapongch** [comment]
I have looked at the source code. It is possible to modify and make changes to the metadata.
