### ISSUE TITLE
Set up API to export dvn 4.5 metadata from test instance

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/dataverse#38]
In Dataverse 4.5, bulk metadata export is accomplished via an API, not a dashboard control. I don't know if the API is already ready to use, but in any case, I don't know how to export it myself. If someone wanted to show me, that could work too.

Thanks.

**Comment by piyapongch** [comment]
The metadata is exported automatically every night and cached. You do not need to export them manually unless, you need latest data that just has been ingested then you can use the API to export them. The API will need to by Dataverse admin on the server. You can find the document here, http://guides.dataverse.org/en/latest/admin/metadataexport.html.
