### ISSUE TITLE
Check that distributorContactEmail is mapped to datasetContactEmail

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/dataverse#46]
Issues [sp4 and ua4](https://docs.google.com/spreadsheets/d/17nPq8ZEgqf7wffOPWUrdaF1duTDr2kg-OvEvvYBjvaM/edit#gid=359603842)

It appears that dv3 fields:
distributorContactName
distributorContactAffiliation
distributorContactEmail

have been renamed in dv4:
datasetContactName
datasetContactAffiliation
datasetContactEmail

Please double check this mapping in the ingest script.

DDI XPath
//codeBook/stdyDscr/citation/distStmt/contact
//codeBook/stdyDscr/citation/distStmt/contact/@affiliation
//codeBook/stdyDscr/citation/distStmt/contact/@email

Note that dv4 DDI output appears to lack these elements, but we believe that is a problem with the dv4 DDI export generation, and not with the ingest process.

**Comment by piyapongch** [comment]
The contact name, email and affiliation go into datasetContactName, datasetContactEmail and datasetAffiliation.
