### ISSUE TITLE
Confirm that Study Version Notes is dropped from dv4

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/dataverse#48]
Issue [sp8](https://docs.google.com/spreadsheets/d/17nPq8ZEgqf7wffOPWUrdaF1duTDr2kg-OvEvvYBjvaM/edit#gid=0)

dv4 appears to have dropped support for Study Version notes.
It's unclear what dv3 db field this corresponds to. The DDI XPath is:
/codeBook/docDscr/citation/verStmt/notes

Instead of asking users to supply a note to describe the changes made in a new version, dv4 can display a table showing the specific changes that were made. However, Version Statement Notes made by users in dv3 will be lost in the absence of a dv4 db field to map them to.

We want to confirm that the information about this change is accurate, so we can include it in our communication with users.

**Comment by piyapongch** [comment]
The Study version notes have been dropped in dv4.

**Comment by johnhuck** [comment]
[Documentation of user-supplied version notes in UAL data](https://docs.google.com/a/ualberta.ca/spreadsheets/d/1gY_SU4MMI8xQy-yq3w__HeUSDgHq7CnbnAYUq0gYLbA/edit?usp=sharing) (system-generated notes excluded).
