### ISSUE TITLE
Check that depDate is being saved in dateOfDeposit dv4 field

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/dataverse#52]
Issue [ua5](https://docs.google.com/spreadsheets/d/17nPq8ZEgqf7wffOPWUrdaF1duTDr2kg-OvEvvYBjvaM/edit#gid=0)

There appears to be an error in the dv4 DDI output, such that the date of deposit value is appearing in the date of distribution elements. However, in examining records in the dv4 interface, it appears date of deposit and date of distribution values are being ingested into the proper fields.

Please check the ingest mapping to confirm this.

**Comment by piyapongch** [comment]
The data of deposit has been set to dateOfDeposit field in dv4. This issue needs to fix in ddi ddi exporter.
