### ISSUE TITLE
Fix date value in citations

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/dataverse#55]
All formatted dataset citations seem to use "2017" rather than a date from the actual metadata. My suspicion is that DV4.5 is pulling the year for the citation from a date that was registered/updated during the data migration.

**Comment by pbinkley** [comment]
I'm not seeing this problem. E.g. for https://dataverse.library.ualberta.ca/dataset.xhtml?persistentId=doi:10.7939/DVN/10100 : in the blue-tinted box the date is 2014, which is the deposit date. In the metadata there is also a production date, 1968. I don't see 2017 being used as a date anywhere. The DOI citation metadata uses 2014: https://ezid.cdlib.org/id/doi:10.7939/DVN/10100 . @johnhuck could you provide an example of incorrect use of 2017 as the date?

**Comment by johnhuck** [comment]
I see examples among unpublished/draft items. Here is one:

https://dataverse.library.ualberta.ca/dataset.xhtml?persistentId=doi:10.7939/DVN/10734&version=DRAFT

**Comment by pbinkley** [comment]
Ah, interesting. Could it be that Dataverse expects to use the date the item was published rather than the date it was deposited, so while it remains unpublished Dataverse uses the date it would show if it were published today?

**Comment by pbinkley** [comment]
This seems to be relevant code: https://github.com/IQSS/dataverse/blob/17f0eaed02f80d9dd3841730ffe3efe9061ab9ef/src/main/java/edu/harvard/iq/dataverse/DataCitation.java#L42-L64 . It looks like in line 50 it's falling back to the current date if it didn't find a citation date or a publication date, but it will take some digging to understand the context.

**Comment by johnhuck** [comment]
That could well be. I had thought it was a more widespread problem, because I couldn't find any datasets that didn't have 2017 in the citation. Maybe I didn't realize I was only looking at drafts, or maybe it corrected itself (?? -- that other problem did). Date of publication is not an editable metadata element, so if that's the source, then your theory would fit.

Here's an example where production date, and deposit date are different from the publication date and distribution date (which is editable). Presumably the source is one of the latter two.

https://dataverse.library.ualberta.ca/dataset.xhtml?persistentId=doi:10.7939/DVN/10810

So it could be I found a non-problem!
