### ISSUE TITLE
Can't delete file from Dataverse

### ISSUE THREAD

**Issue by JamesDoiron** [ualbertalib/dataverse#58]
A U of A user - Jonathan Cale - contacted us to indicate that he was having issues downloading a file from one of his unpublished studies, which he should be able to do. He sees the delete option and uses it, but it does not do anything.

I have accessed both the production and dev8 test servers as Admin and tried to delete the same file, and am experiencing the same issue. As well, I did try deleting another test file that I had previously uploaded to the dev8 server and was successful. 

The study he is looking at is: 
Cale, Jonathan; Muskens, Marlena; Najar, Ahmed; Ishangulyyeva, Guncha; Hussain, Altaf; Kanekar, Sanat; Klutsch, Jennifer; Taft, Spencer; Erbilgin, Nadir, 2017, "Replication data for: Rapid monoterpene induction promotes the susceptibility of a novel host pine to mountain pine beetle colonization but not to beetle-vectored fungi", doi:10.7939/DVN/10850, UAL Dataverse, DRAFT VERSION

The specific file he is trying to delete is: "Cale_et_al_Monoterpene_induction_data.csv"

I have also confirmed that Jonathan has both data curator and administrator permissions. 

Might just be an easy answer - hoping!

**Comment by piyapongch** [comment]
I will investigate the problem. I will need to get data from the production server to unixdev8.

**Comment by piyapongch** [comment]
The category data migration step from DV 3.6 to 4.5 has not migrated correctly. Users can see tags on the files, but they can not delete them. The datasetfilecategory table stores wrong dataset_id that has not been found in dataset table. To fix the problem, the dataset_id fields in datafilecategory table need to be updated to correct ids in dataset table. Here are step to fix the problem on the files that the user reported manually.
- Delete tags from both files.
- Delete the first file using user interface and check log file for a dataset_id.
- ```dvndb=# delete from datafilecategory where dataset_id = {dateset_id found in log file};```
- Delete file using user interface, this should remove the file from dataset.
Repeat the last 3 steps for the second file.

I will schedule to implement the solution with Henry. We will try these steps on the development server first to make sure the steps are working properly. We will not delete the files on the production server. I will let you know so you can notify the user to perform the deletion.

**Comment by piyapongch** [comment]
I have created an issue, #59 for fixing the tags' data.

**Comment by JamesDoiron** [comment]
Great, thanks Piyapong! I've let our user know that we were looking at the issue this week and that I would be in touch when I return to the office next week. 

Cheers,

James

**Comment by piyapongch** [comment]
I have applied the fix on the production server. The user should be able to delete the files.
