### ISSUE TITLE
Dataverse: [Spike] Investigate Grant Agency field in upgrade

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/dataverse#61]
@johnhuck found that the Grant Agency field was absent in the DDI export of upgraded content in our upgrade test. We need to know: is the value actually missing in the database, or is it present in the database but not mapped correctly into the DDI? A database dump from Henry is avaialble to check this.

**Comment by johnhuck** [comment]
Having access to the 4.9.1 deployment on unixdev8 again, I checked the studies I had identified where the grantNo element was missing from the DDI output. I looked in the GUI, signed in as dataverseAdmin. The metadata was plainly there, so the absence of the element in the DDI output from 4.9.1 is almost certainly a question of a change in the script or process that generates that output.

**Comment by pbinkley** [comment]
The upgrade to 4.9.1 is complete and this problem hasn't come back, so I'll close this issue.
