### ISSUE TITLE
Upgrade dataverse from 4.5.1 to 4.9.1

### ISSUE THREAD

**Issue by henryzhang87** [ualbertalib/dataverse#62]
After upgrading unixdev8 from 4.5.1 to 4.9.1, we would like to upgrade our production dataverse
from 4.5.1 to 4.9.1 as well.

Notes:  The production is different from dev in that it has SSL enabled and uses shibboleth.

**Comment by weiweishi** [comment]
Upgrade Plan outlined here:

https://drive.google.com/file/d/1JhVvkuYW-becJUqzNDv_BvM56FgWJhmv/view?ts=5b6dfd7b

**Comment by weiweishi** [comment]
The upgrade was completed successfully. 

Post upgrade discussion is captured in the document: https://docs.google.com/document/d/1F0Qm80DRwTx1-yPNG_j07yFt0ktX9A4Okq7ZRvFH5ik/edit#
