### ISSUE TITLE
Dataverse: Transition to Datacite DOI API

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/dataverse#64]
We are transitioning from EZID from National Research Council's Datacite service because of this:
http://www.cdlib.org/cdlinfo/2017/08/04/ezid-doi-service-is-evolving/

What is required in the short term:
configuration of Dataverse; it looks simple, though 
- [x] Change the configuration of Dataverse to switch our DOI minting service to use Datacite. It may need to be done partly via JVM options and partly via the configuration REST API http://guides.dataverse.org/en/4.9.1/installation/config.html?highlight=doi .
- [x] Deployment of the switch need to coordinate with Jupiter's deployment as DataCite doesn’t recognize shoulders and deals only at the prefix level
- [x] We have several reserved DOIs in our EZID account. Before we migrate in production, these need to be manually created as draft IDs in our Datacite account, so that Dataverse users who are counting on using the reserved ids in unpublished objects will be able to do so. Once they are created as draft DOIs, we expect that Dataverse will manage them normally. We need to confirm that metadata will be attached to them when they are published, since it will be easiest to create them without metadata.

**Comment by pbinkley** [comment]
@piyapongch will look into how to test this in advance

**Comment by pbinkley** [comment]
Datacite account for testing is CISTI.UAL (password to be shared offline). Test prefix: 10.21967 . API end points:  https://mds.test.datacite.org or https://ez.test.datacite.org - we'll be using ez.test for our EZID API work in Dataverse and Jupiter. Support: https://support.datacite.org.

**Comment by piyapongch** [comment]
This issue has been implemented on the production server.
