### ISSUE TITLE
Upgrade to 4.9.4

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/dataverse#70]
**Tag**
v4.9.4 https://github.com/IQSS/dataverse/releases/tag/v4.9.4

**Test checklist**
Perform the following tests on the staging server.

- [x] Shibboleth login (testing accounts like Henry’s which is linked to ccid but identifier is not e-mail, vs. Peter’s which does),
- [x] Basic searches
- [x] Dataverse creation
- [x] Dataset uploads & downloads
- [x] Dataset versioning
- [x] Testing views as a function of different permission settings (e.g., standard user, Dataverse administrator, Dataverse Systems Administrator)
- [x] Terms of Use feature
- [x] Guestbook feature
- [x] OAI List records: ```/oai?verb=ListRecords&metadataPrefix=oai_ddi``` (note: the default set may not be built immediately). Should return set of XML DDI records.
- [x] Metadata check

**Notes**
Any other information about this release, e.g.

- new features (which may require decisions by the service manager) - **none**
- content changes (which may require extra attention to checking metadata) - **none**

**Comment by pbinkley** [comment]
Guestbook: I created one for https://zk-dev3.library.ualberta.ca/dataverse/JamesDTest , and chose two out of the four default fields and added a new multiple choice field. When I download a file from an incognito window (so I'm not logged in), it does not challenge me with the guestbook form.

**Comment by johnhuck** [comment]
I completed some basic spot checks for metadata, as documented [here](https://docs.google.com/document/d/1Bj6j7Rtn-G_SkyNRdUE8CGy5wDBD3NmbD5mkjZMwE7o/edit?usp=sharing). No problems found, except the minor observation that the ampersand encoding problem identified in 4.9.1 has not been addressed and so carried forward. Since this issue did not block the upgrade to 4.9.1, there is no reason for it to block this upgrade. Ideally we could look at it and resolve it at some point. Cheers!

**Comment by pbinkley** [comment]
Update: we want to test whether the Guestbook problem applies only to newly created guestbooks or also to existing ones.

**Comment by pbinkley** [comment]
Result: the Guestbook feature does not work in our 4.9.4 instance. We will therefore not deploy to production until we've debugged this.

**Comment by piyapongch** [comment]
The Guestbook feature has been fixed. I, @piyapongch have worked with @henryzhang87 and upgraded the production server to v4.9.4. This is our current production version.
