### ISSUE TITLE
Dataverse logo when posting to Facebook is Harvard's, not ours

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/dataverse#71]
Here's what a Facebook posting of a dataset looks like:

![image](https://user-images.githubusercontent.com/272816/49403766-d7611e80-f70a-11e8-8146-3eb778589003.png)

The image is from [src/main/webapp/resources/images/dataverseproject.png](https://github.com/ualbertalib/dataverse/blob/develop/src/main/webapp/resources/images/dataverseproject.png). It seems to be linked here in our html:

```
<link type="image/png" rel="image_src" href="/javax.faces.resource/images/dataverseproject.png.xhtml" />
```

which is [hardcoded in the template](https://github.com/ualbertalib/dataverse/blob/56c5608a30fcdfbd10578e34b94b346ab2b55038/src/main/webapp/dataverse_template.xhtml#L27).

We should replace it with an appropriate UAlberta logo.

**Comment by piyapongch** [comment]
This issue will be discussed in the next Dataverse migration meeting, @johnhuck @henryzhang87 @piyapongch.

**Comment by piyapongch** [comment]
@johnhuck, Can you provide me the logo you want to replace? I will update the application. Then, we need to update the war file in Henry's upgrade scripts? Thanks,

**Comment by johnhuck** [comment]
@piyapongch I'm not sure exactly what the image should be. In Peter's example, it's not actually the Harvard logo, but the Dataverse project logo. Do we want one that says U of A, or UAL Dataverse or what. Do we have an image we already use for something like ERA? I'll follow up with James. I'd like his input on these questions.

**Comment by johnhuck** [comment]
James Doiron and I discussed this issue today and concluded that we will not take any action on this issue for these reasons: the logo is the Dataverse logo, not Harvard's; and this is not a high-priority issue at the present time.
